### ISSUE TITLE
Ask for dcos-version.json raised an exception

### ISSUE THREAD

**Issue by chrisdupuy** [mesosphere/dcos-commons#112]
When 
```curl $$SERVER$$/dcos-metadata/dcos-version.json```
I get : 
```
{
  "version": "1.7-open",
  "dcos-image-commit": "14509fe1e7899f439527fb39867194c7a425c771",
  "bootstrap-id": "3a2b7e03c45cd615da8dfb1b103943894652cd71"
}
```
Then when installing Universe Kafka (or Confluent Kafka) in 1.1.11, first broker "broker-0" is correctly up. The main kafka task complains starting other nodes due to resources offers (declining offer), even if all resources are available.
One exception raised : 
```
WARN  [2016-09-06 08:48:49,453] org.apache.mesos.dcos.Capabilities: Unable to parse version string for Named Vip
! java.lang.NumberFormatException: For input string: "7-open"
! at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_91]
! at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_91]
! at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_91]
! at org.apache.mesos.dcos.DcosVersion$Elements.getSecondElement(DcosVersion.java:46) ~[dcos-commons-0.4.37-SNAPSHOT.jar:na]
! at org.apache.mesos.dcos.Capabilities.supportsNamedVips(Capabilities.java:26) ~[dcos-commons-0.4.37-SNAPSHOT.jar:na]
! at com.mesosphere.dcos.kafka.offer.PersistentOfferRequirementProvider.getNewOfferRequirementInternal(PersistentOfferRequirementProvider.java:425) [kafka-scheduler.jar:na]
! at com.mesosphere.dcos.kafka.offer.PersistentOfferRequirementProvider.getNewOfferRequirement(PersistentOfferRequirementProvider.java:55) [kafka-scheduler.jar:na]
! at com.mesosphere.dcos.kafka.plan.KafkaUpdateBlock.getOfferRequirement(KafkaUpdateBlock.java:208) [kafka-scheduler.jar:na]
! at com.mesosphere.dcos.kafka.plan.KafkaUpdateBlock.start(KafkaUpdateBlock.java:85) [kafka-scheduler.jar:na]
! at org.apache.mesos.scheduler.plan.DefaultStageScheduler.resourceOffers(DefaultStageScheduler.java:59) [dcos-commons-0.4.37-SNAPSHOT.jar:na]
! at com.mesosphere.dcos.kafka.scheduler.KafkaScheduler.resourceOffers(KafkaScheduler.java:271) [kafka-scheduler.jar:na]```

At https://github.com/mesosphere/dcos-commons/blob/master/src/main/java/org/apache/mesos/dcos/DcosVersion.java#L46, 
a String (dcos version = 1.7-open) cannot be casted into an Integer.

**Comment by gabrielhartmann** [comment]
@chrisdupuy:  Apologies for the late reply.  This has been resolved for some time here: https://github.com/mesosphere/dcos-commons/blob/99a40b765cf4fc6e4a6226add2f1ccaef2ce22cf/sdk/scheduler/src/main/java/org/apache/mesos/dcos/Capabilities.java#L29-L32
