### ISSUE TITLE
Getting started fail at building step

### ISSUE THREAD

**Issue by IxDay** [mesosphere/dcos-commons#1714]
I cloned the directory and followed the instructions from here: https://mesosphere.github.io/dcos-commons/developer-guide.html

But at step 4 of https://mesosphere.github.io/dcos-commons/developer-guide.html#getting-started the build fails with the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':myframework:test'.
```
And when going to test report got this error:

```
com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [map type; class java.util.LinkedHashMap, [simple type, class java.lang.String] -> [simple type, class java.lang.String]] from String value (''); no single-String constructor/factory method
 at [Source: [B@5149f1bb; line: 19, column: 13] (through reference chain: com.mesosphere.sdk.specification.yaml.RawServiceSpec["pods"]->com.mesosphere.sdk.specification.yaml.WriteOnceLinkedHashMap["myframework"]->com.mesosphere.sdk.specification.yaml.RawPod["tasks"]->com.mesosphere.sdk.specification.yaml.WriteOnceLinkedHashMap["node"]->com.mesosphere.sdk.specification.yaml.RawTask["env"])
```

**Comment by ignaciomosca** [comment]
Currently having the same problem.

The whole stacktrace is:

```
testsuite com.mesosphere.sdk.fis.scheduler.ServiceTest:
  testcase com.mesosphere.sdk.fis.scheduler.ServiceTest > testSpec: com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [map type; class java.util.LinkedHashMap, [simple type, class java.lang.String] -> [simple type, class java.lang.String]] from String value (''); no single-String constructor/factory method
     at [Source: [B@7133625b; line: 19, column: 13] (through reference chain: com.mesosphere.sdk.specification.yaml.RawServiceSpec["pods"]->com.mesosphere.sdk.specification.yaml.WriteOnceLinkedHashMap["empty"]->com.mesosphere.sdk.specification.yaml.RawPod["tasks"]->com.mesosphere.sdk.specification.yaml.WriteOnceLinkedHashMap["node"]->com.mesosphere.sdk.specification.yaml.RawTask["env"])
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:878)
    at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:281)
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:284)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:334)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:495)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:495)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2819)
    at com.mesosphere.sdk.specification.yaml.RawServiceSpec$Builder.build(RawServiceSpec.java:72)
    at com.mesosphere.sdk.testing.ServiceTestRunner.run(ServiceTestRunner.java:206)
      
      205:                   .setEnv(schedulerEnvironment)
      206: >                 .build();
      207:   
      
    at com.mesosphere.sdk.fis.scheduler.ServiceTest.testSpec(ServiceTest.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```

**Comment by ignaciomosca** [comment]
@IxDay I solved it by adding a SLEEP_DURATION as an env child like this:
```
env:
          SLEEP_DURATION: {{SLEEP_DURATION}}
```

**Comment by elezar** [comment]
It could be that the `env` section is empty without this `SLEEP_DURATION` specified. You could try just removing the `env` section in `svc.yml` entirely.

**Comment by ignaciomosca** [comment]
Yes, I did that and it worked too. I even created a PR for it (https://github.com/mesosphere/dcos-commons/pull/1770). 

I closed it because of the following reasons:

- I don't think it's the way to go.
- Some integration tests failed (a few, and maybe because of unrelated issues, but they failed nonetheless)
- There's an explicit reference to `SLEEP_DURATION` in this line of `svc.yml`:
`cmd: "echo template >> template-container-path/output && sleep $SLEEP_DURATION"`

**Comment by elezar** [comment]
Sorry. I missed that.

**Comment by frankscholten** [comment]
Duplicate of https://github.com/mesosphere/dcos-commons/issues/2282
