### ISSUE TITLE
NullPointerException when an agent is restarted and executor re-registers with the agent

### ISSUE THREAD

**Issue by verma7** [mesosphere/dcos-commons#372]
This happened in our production clusters when an agent was restarted:
```I1208 17:56:05.810570 116560 exec.cpp:259] Executor re-registered on agent 09a39793-0f2c-4ec9-b29a-c011b1b4f039-S1388
java.lang.NullPointerException
	at org.apache.mesos.executor.CustomExecutor.reregistered(CustomExecutor.java:52)
	at com.mesosphere.dcos.cassandra.executor.CassandraExecutor.reregistered(CassandraExecutor.java:75)
```

I think the fix is to change https://github.com/mesosphere/dcos-commons/blob/8c8177e692657797e142e1b9c62666be6327000f/sdk/executor/src/main/java/com/mesosphere/sdk/executor/CustomExecutor.java#L54:
from
```
LOGGER.info("Re-registered executor: {}", executorInfo.getExecutorId());
```
to 
```
LOGGER.info("Re-registered executor on slave: {}", slaveInfo.getId());
```

**Comment by verma7** [comment]
@gabrielhartmann @nickbp

**Comment by mgummelt** [comment]
Thanks.  We're looking into it.

**Comment by verma7** [comment]
The PR has been merged.
