### ISSUE TITLE
'python3: no such file or directory' error when running 'build.sh local' for helloworld service

### ISSUE THREAD

**Issue by frankscholten** [mesosphere/dcos-commons#939]
From inside the vagrant box:

```
[vagrant@dcos-docker-sdk helloworld]$ ./build.sh local
PUBLISH_STEP=local
FRAMEWORK_NAME=hello-world
FRAMEWORK_DIR=/dcos-commons/frameworks/helloworld
ARTIFACT_FILES=/dcos-commons/frameworks/helloworld/build/distributions/executor.zip /dcos-commons/frameworks/helloworld/build/distributions/hello-world-scheduler.zip
/usr/bin/env: python3: No such file or directory
```

**Comment by frankscholten** [comment]
I installed python3 with these instructions http://ask.xmodulo.com/install-python3-centos.html but now I get enother error when running `./build.sh local`

```
Building Python CLI wrapper (DC/OS 1.7 / universe-2.x compatibility)
Packing 3 executables in python wrapper:
- /dcos-commons/frameworks/helloworld/cli/dcos-hello-world/dcos-hello-world-darwin
- /dcos-commons/frameworks/helloworld/cli/dcos-hello-world/dcos-hello-world-linux
- /dcos-commons/frameworks/helloworld/cli/dcos-hello-world/dcos-hello-world.exe
[STATUS] build:hello-world success: Build succeeded
Launching HTTP artifact server
  File "/dcos-commons/tools/publish_http.py", line 172
    os.chmod(httpd_py_path, 0744)
                               ^
SyntaxError: invalid token
```

**Comment by mnp** [comment]
Try this PR?  https://github.com/mnp/dcos-commons/pull/1

**Comment by frankscholten** [comment]
@mnp I made progress after applying your PR but then I got this error:

```
---
Copying 7 artifacts into /tmp/dcos-http-hello-world/:
- /tmp/dcos-http-hello-world/bootstrap.zip
- /tmp/dcos-http-hello-world/dcos-hello-world-darwin
- /tmp/dcos-http-hello-world/dcos-hello-world.exe
- /tmp/dcos-http-hello-world/dcos-hello-world-linux
- /tmp/dcos-http-hello-world/bin_wrapper-0.0.1-py2.py3-none-any.whl
- /tmp/dcos-http-hello-world/executor.zip
- /tmp/dcos-http-hello-world/hello-world-scheduler.zip
[STATUS]  success: Copied stub universe and 7 artifacts (http://172.17.0.1:34226/stub-universe-hello-world.zip)
http://172.17.0.1:34226/stub-universe-hello-world.zip
Checking for duplicate repositories: name=hello-world-local, url=http://172.17.0.1:34226/stub-universe-hello-world.zip
URL [http://172.17.0.2/package/repository/list] is unreachable: HTTPConnectionPool(host='172.17.0.2', port=80): Max retries exceeded with url: /package/repository/list (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8c78401a58>: Failed to establish a new connection: [Errno 113] No route to host',))
Traceback (most recent call last):
  File "/dcos-commons/tools/publish_http.py", line 239, in <module>
    sys.exit(main(sys.argv))
  File "/dcos-commons/tools/publish_http.py", line 225, in main
    repo_added = publisher.add_repo_to_cli(universe_url)
  File "/dcos-commons/tools/publish_http.py", line 189, in add_repo_to_cli
    cur_universes = subprocess.check_output('dcos package repo list --json'.split()).decode('utf-8')
  File "/usr/local/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dcos', 'package', 'repo', 'list', '--json']' returned non-zero exit status 1
```

The script tries to connect to `http://172.17.0.2/package/repository/list` but the VM's IP is 172.17.0.1 and I don't know where it gets 172.17.0.2 from.

**Comment by mnp** [comment]
Update - I've just been installing the centos Python3 as workaround.  This should be part of the vbox image when they get around to making a new one.

    sudo yum install python34

That's it.  One thing I need to do for my corp network might apply to others.  Our $ITDEPT blocks outbound DNS, which is a problem for dcos-spartan, which has hardcoded public nameserver IP's in its configs for **upstream_resolver.**  After standing up the containers, I make a spartan config with our approved nameserver, push to the containers, bounce spartan.

    for i in `docker ps -q`; do  
        docker cp spartan.json $i:/opt/mesosphere/etc/spartan.json
        docker exec -it $i systemctl restart dcos-spartan
    done

After that, all references to mesosphere.com will work for universe, container pulls, Yum jobs like the above Python 3, etc.
